# Generated by Django 4.0.7 on 2023-03-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
