# Generated by Django 4.0.7 on 2023-03-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalmarketingapp', '0003_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
