# Generated by Django 4.0.7 on 2023-03-09 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('digitalmarketingapp', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mobiles', models.CharField(max_length=10)),
                ('defaultbalance', models.IntegerField(default=0)),
                ('senderIds', models.CharField(max_length=10)),
            ],
        ),
    ]
